### ISSUE TITLE
Error: Import AWS Lambda ends w/ an error

### ISSUE THREAD

**Issue by mosheka** [GoogleCloudPlatform/terraformer#1599]
I'm trying to import AWS Lambda and get an error related to GetPolicy.
There is an open question reg. it in StackOverflow that was opened a week ago.

My feeling that it is related to Line 104 @
https://github.com/GoogleCloudPlatform/terraformer/blob/master/providers/aws/lambda.go

```
sudo ./terraformer import aws --resources=lambda --regions=eu-west-1
2023/01/04 23:01:50 aws importing region eu-west-1
2023/01/04 23:01:50 aws importing... lambda
2023/01/04 23:01:51 aws error initializing resources in service lambda, err: operation error Lambda: GetPolicy, https response error StatusCode: 404, RequestID: 67d8e12c-adf2-405f-9d65-5045981e0cb7, ResourceNotFoundException: The resource you requested does not exist.
2023/01/04 23:01:51 aws Connecting....
```

**Comment by reinpetersen-serenaandlily** [comment]
i have same issue.. @mosheka can you add link to related stackoverflow please?

**Comment by reinpetersen-serenaandlily** [comment]
@mosheka - i have been looking at cloudtrail logs and it appears that it fails on finding the first lambda with no resource policy (inline policy doesn't cut it apparently). so, if you can put resource policy on all your lambdas you should (theoretically because im still going through my lambdas to add missing policy) get it to work

**Comment by mosheka** [comment]
Nice, but it is still a bug (especially when you want this export for audit needs).

**Comment by morjanmihail** [comment]
This is still an issue that wasn't fixed. I'm having the same problem.

**Comment by mixMugz** [comment]
Same problem. I have a lot of lambda without policy and cant add policy right now. How I can import all of them

**Comment by simouda** [comment]
Same issue here also. Any workaround?

**Comment by apedelty-avantus** [comment]
Can we re-open this? It's still an issue.

**Comment by oliverhr** [comment]
This still an issue on `version v0.8.24`

**Comment by fpultera** [comment]
Same issue here also.

**Comment by d3vpasha** [comment]
This is still an issue. Please re-open the issue

**Comment by nickyfoster** [comment]
Still relevant. Please reopen this issue.

**Comment by mmigliari** [comment]
Almost a year has passed, and this issue is still relevant.  Is it me, or is terraformer not keeping up since terraform introduced  the -generate-config-out option in plan for resources listed in import blocks?

This bug basically makes importing lambdas completely broken.  What a shame, since terraformer is such a cool project.

**Comment by OleksandrTimoshenko** [comment]
This is still an issue. Please re-open the issue

**Comment by davidpelayo** [comment]
It would be awesome to have this fixed as soon as possible!

**Comment by jomakori** [comment]
Need the fix as well - terracognita also has a bug with lambda - but more-so on the templating front

**Comment by ambronet** [comment]
How are we supposed to get this resolved in macOS? I tried to install terraformer using homebrew with the following command:

`brew install --HEAD --force terraformer`

But it failed with:

```
==> go build -ldflags=-s -w
Last 15 lines from /Users/xxx/Library/Logs/Homebrew/terraformer/01.go:
        __const          addr=0x10a184530, size=0x00000670, fileOffset=0x0a184530
        __rodata         addr=0x10a184ba0, size=0x028be4a0, fileOffset=0x0a184ba0
        __typelink       addr=0x10ca43040, size=0x0007ee20, fileOffset=0x0ca43040
        __itablink       addr=0x10cac1e60, size=0x00036db0, fileOffset=0x0cac1e60
        __gopclntab      addr=0x10caf8c20, size=0x06a6e038, fileOffset=0x0caf8c20
    __DATA               addr=0x113568000, size=0x002b8000, fileOffset=0x13568000
        __data           addr=0x113568000, size=0x0005af00, fileOffset=0x13568000
        __go_buildinfo   addr=0x1135c2f00, size=0x00008e50, fileOffset=0x135c2f00
        __noptrdata      addr=0x1135cbd60, size=0x001e4b73, fileOffset=0x135cbd60
        __bss            addr=0x1137b08e0, size=0x000578a4, fileOffset=0x00000000
        __noptrbss       addr=0x1138081a0, size=0x00015b90, fileOffset=0x00000000
        __common         addr=0x11381dd30, size=0x00000018, fileOffset=0x00000000
    __LINKEDIT           addr=0x113820000, size=0x03e08000, fileOffset=0x137b4000
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by nikolasd** [comment]
@sergeylanzman is there any new release containing this fix coming soon?

**Comment by Gregg-Casey** [comment]
@sergeylanzman apparently this is NOT really fixed.  We are still getting this error.

**Comment by ShaneCray** [comment]
@sergeylanzman I'm seeing this issue as well

**Comment by dennismartini** [comment]
Same problem here

**Comment by ktx-mega** [comment]
Hello, I have the same problem

**Comment by erados** [comment]
same problem

**Comment by eazevedo-cloud** [comment]
Hi guys, I forked and changed the lambda code to fix that issue. Just tested successfully!

![image](https://github.com/user-attachments/assets/75a5e7c6-9332-4444-862c-068e95d44202)

![image](https://github.com/user-attachments/assets/264a179e-f246-4489-baec-4d418af92c03)

Not a big deal, but hope it can help
https://github.com/eazevedo-cloud/terraformer/commit/ba6271cfae33d5157d4f0f637e19b1317c5d2a74

Cheers!

**Comment by anson00** [comment]
using the forked git provided by eazevedo-cloud. git clone it and run it. it really worked well.

<img width="721" alt="image" src="https://github.com/user-attachments/assets/c0049192-2fef-406d-a420-153921533649">


Here provided the way to install and run it:
1. **Clone the repo with the following command**
`git clone https://github.com/eazevedo-cloud/terraformer.git`

2. **It will install into a directory called terraformer. You may rename into terraformer-forked so that you could allow both official terraform and terraformer exist in your machine**
`mv terraformer terrafomer-forked`

3. **You may install Go in your machine.**

4. **Build the forked code with Go**
`go build -o terraformer-forked`

5. **Move the file to the user program file** (In case you are using windows, you may move the installed item to Program files, and add the program files to Environment Variables)
`sudo mv terraformer-forked /usr/local/bin/`

6. **(Optional) Verify the installation**
`terraformer-forked version`

6. **Now you may run the command of import instead of terraformer, change to terraformer-forked**

provided a sample:
`terraformer-forked import aws --resources="lambda" --regions="ap-southeast-1"`

Hope it helps.

Cheers!!!

**Comment by juttayaya** [comment]
Excellent instructions of the forked terraformer build

Just a note that the Go version must be 1.18. I used 1.18.10

**Comment by worked** [comment]
Minor thing. `mv terraformer terrafomer-forked` should be `mv terraformer terraformer-forked`

**Comment by worked** [comment]
> Excellent instructions of the forked terraformer build
> 
> Just a note that the Go version must be 1.18. I used 1.18.10

For those less GoLang inclined, navigate into the terraformer-forked directory and open go.mod file, at the top, update version to 1.18.0.

**Comment by kwilsonmg** [comment]
@sergeylanzman can we re-open this? It still isn't resolved.

**Comment by CepheiA** [comment]
Can we re-open this? It's still an issue.
