### ISSUE TITLE
Support for 'google_organization_policy' resource

### ISSUE THREAD

**Issue by anubbhavm** [GoogleCloudPlatform/terraformer#369]
Organization policy doesn't seem to be a supported GCP resource. It'll be great to have support for it per request from a customer.

**Comment by sergeylanzman** [comment]
I try to add google_organization_policy here https://github.com/GoogleCloudPlatform/terraformer/pull/376
BUT I can't test this code, because I don't have organization with folder and projects.

If you know GCP folder API, it's can be help.

**Comment by anubbhavm** [comment]
Yes, I can test it out. Could you confirm if it's merged in the master and if I can download the binary?

**Comment by anubbhavm** [comment]
Also, --organization doesn't seem to be a supported flag. We might want to add that as a feature to capture resources (org policies) at an org level.

For example, I ran this command and got the error:

terraformer import google --resources=organizationPolicy --connect=true --regions=us-central1 --organization=852514890226

unknown flag: --organization
gcp: organizationPolicy not supported service

Is this the right way to access the org policy resource and the organization flag?
Should I create another issue for this? Please advise.

**Comment by sergeylanzman** [comment]
I added now option `--organization` here https://github.com/GoogleCloudPlatform/terraformer/pull/376 , still need set project(not used but need set)
Can you try used this with custom branch?

**Comment by anubbhavm** [comment]
Used the gcp-add-organization-policy branch. Getting this error:

terraformer import google --resources=organizationPolicy --connect=true --regions=us-central1 --organization=852514890226 --project=corebuild-10022019

unknown flag: --resources

**Comment by anubbhavm** [comment]
Tried using the gcp-add-organization-policy branch. Getting the below error:

terraformer import google --resources=organizationPolicy --connect=true --regions=us-central1 --organization=852514890226 --project=corebuild-10022019
unknown flag: --resources

**Comment by sergeylanzman** [comment]
How  you build from this branch?

**Comment by anubbhavm** [comment]
1. Run git clone <terraformer repo>
2. Run GO111MODULE=on go mod vendor
3. go run build/main.go {google}
4. Run terraform init against an init.tf file to install the plugins required for your platform. For example, if you need plugins for the google provider, init.tf should contain:
provider "google" {}

**Comment by sergeylanzman** [comment]
`go run build/main.go {google}` or `go run build/main.go google`? 
try use only `go run build/main.go google`

**Comment by anubbhavm** [comment]
Not able to read org policies. Please see error below:

terraformer import google --resources=organizationPolicy --connect=true --organization=852514890226 --projects=corebuild-10022019
2020/02/07 16:58:40 google importing project corebuild-10022019 region global
2020/02/07 16:58:40 google importing... organizationPolicy
2020/02/07 16:58:41 Refreshing state... google_organization_policy.tfer--852514890226-002D-constraints-002F-iam-002E-disableServiceAccountCreation
2020/02/07 16:58:41 Refreshing state... google_organization_policy.tfer--852514890226-002D-constraints-002F-sql-002E-restrictPublicIp
2020/02/07 16:58:41 Refreshing state... google_organization_policy.tfer--852514890226-002D-constraints-002F-cloudfunctions-002E-allowedIngressSettings
2020/02/07 16:58:41 ERROR: Read resource response is null for resource google_organization_policy.tfer--852514890226-002D-constraints-002F-cloudfunctions-002E-allowedIngressSettings
2020/02/07 16:58:41 ERROR: Read resource response is null for resource google_organization_policy.tfer--852514890226-002D-constraints-002F-iam-002E-disableServiceAccountCreation
2020/02/07 16:58:41 ERROR: Read resource response is null for resource google_organization_policy.tfer--852514890226-002D-constraints-002F-sql-002E-restrictPublicIp
2020/02/07 16:58:41 ERROR: Unable to refresh resource tfer--852514890226-002D-constraints-002F-cloudfunctions-002E-allowedIngressSettings
2020/02/07 16:58:41 ERROR: Unable to refresh resource tfer--852514890226-002D-constraints-002F-iam-002E-disableServiceAccountCreation
2020/02/07 16:58:41 ERROR: Unable to refresh resource tfer--852514890226-002D-constraints-002F-sql-002E-restrictPublicIp
2020/02/07 16:58:41 google Connecting....
2020/02/07 16:58:41 google save organizationPolicy
2020/02/07 16:58:41 google save tfstate for organizationPolicy

**Comment by sergeylanzman** [comment]
Fixed, I added `org_id` as init parameters.
Can you try again?

**Comment by anubbhavm** [comment]
I tried again pulling the latest changes from the branch "gcp-add-organization-policy". Still failing. Please see below.

terraformer import google --resources=organizationPolicy --connect=true --organization=852514890226 --projects=corebuild-10022019
2020/02/10 10:17:07 google importing project corebuild-10022019 region global
2020/02/10 10:17:07 google importing... organizationPolicy
2020/02/10 10:17:08 Refreshing state... google_organization_policy.tfer--852514890226-002D-constraints-002F-cloudfunctions-002E-allowedIngressSettings
2020/02/10 10:17:08 Refreshing state... google_organization_policy.tfer--852514890226-002D-constraints-002F-iam-002E-disableServiceAccountCreation
2020/02/10 10:17:08 Refreshing state... google_organization_policy.tfer--852514890226-002D-constraints-002F-sql-002E-restrictPublicIp
2020/02/10 10:17:08 ERROR: Read resource response is null for resource google_organization_policy.tfer--852514890226-002D-constraints-002F-cloudfunctions-002E-allowedIngressSettings
2020/02/10 10:17:08 ERROR: Read resource response is null for resource google_organization_policy.tfer--852514890226-002D-constraints-002F-sql-002E-restrictPublicIp
2020/02/10 10:17:08 ERROR: Read resource response is null for resource google_organization_policy.tfer--852514890226-002D-constraints-002F-iam-002E-disableServiceAccountCreation
2020/02/10 10:17:08 ERROR: Unable to refresh resource tfer--852514890226-002D-constraints-002F-cloudfunctions-002E-allowedIngressSettings
2020/02/10 10:17:08 ERROR: Unable to refresh resource tfer--852514890226-002D-constraints-002F-iam-002E-disableServiceAccountCreation
2020/02/10 10:17:08 ERROR: Unable to refresh resource tfer--852514890226-002D-constraints-002F-sql-002E-restrictPublicIp
2020/02/10 10:17:08 google Connecting....
2020/02/10 10:17:08 google save organizationPolicy
2020/02/10 10:17:08 google save tfstate for organizationPolicy

**Comment by anubbhavm** [comment]
hey, just checking if you got a chance to look into this?
