### ISSUE TITLE
v0.8.8 fails to import GCE Instances

### ISSUE THREAD

**Issue by cloud-orange** [GoogleCloudPlatform/terraformer#604]
Attempted to import GCE instances via the `instances` service and got the following
``` bash
2020/09/09 13:58:59 google importing project <redacted> region us-central1
2020/09/09 13:58:59 google importing... instances
2020/09/09 13:58:59 gcp: instances not supported service
```

Checked terraform configs, terraform version and GCP IAM permissions to no avail.
Downgrading terraformer to v0.8.7 fixes the issue for me

Tried the following with the v0.8.8 release:
- Tried with terraform versions used in previous imports: v0.12.24, v0.12.29 and got no change
- Tried GCP providers versions used in previous imports: 3.33.0 and 3.26.0 and got no change
- Updated Terraform and to GCP provider to their latest versions 0.13.2 and 3.38.0 respectively, still no change.

Only the downgrade of terraformer to 0.8.7 from 0.8.8 appears to solve the issue which strongly suggests an error in the latest release.

**Comment by bigjew92** [comment]
This also effects Cloud SQL. Downgraded to 0.8.7 and that seemed to help. Might effect more services. Anything that is essentially GCE underneath.

**Comment by dvasdekis** [comment]
> This also effects Cloud SQL. Downgraded to 0.8.7 and that seemed to help. Might effect more services. Anything that is essentially GCE underneath.
I'm still having this problem today with GCP instances, but it was able to scan Cloud SQL instances when I built from [this commit](https://github.com/GoogleCloudPlatform/terraformer/commit/385e5a45c04803484de43f03324e2d3cf82c5c2f).

**Comment by tsarlewey** [comment]
I've had this issue. The fix for me specifying the regions in which you're trying to get the instances.
E.g. 

`terraformer import google --resources=instances --project={PROJECT_ID} --regions=us-central1`

My versions:
Terraform v0.12.29
 + provider.google v3.44.0
Terraformer version v0.8.8

I've tried using the latest with everything but through trial and error found that this was stable for me.

**Comment by sergeylanzman** [comment]
fixed!
In master now

**Comment by ingramchen** [comment]
Is the issue resolved ?
I try 0.8.9 release (linux) but it still not work:

```
# ~/terraformer version
Terraformer v0.8.9
# ~/terraformer plan google --projects=foo --regions=asia-east1 --resources="instances" 
2020/11/24 17:06:49 google importing project foo region asia-east1
2020/11/24 17:06:50 google importing... instances
2020/11/24 17:06:50 gcp: instances not supported service
```

**Comment by tsarlewey** [comment]
> Is the issue resolved ?
> I try 0.8.9 release (linux, terraform 0.13) but it still not work:
> 
> ```
> # ~/terraformer version
> Terraformer v0.8.9
> # ~/terraformer plan google --projects=foo --regions=asia-east1 --resources="instances" 
> 2020/11/24 17:06:49 google importing project foo region asia-east1
> 2020/11/24 17:06:50 google importing... instances
> 2020/11/24 17:06:50 gcp: instances not supported service
> ```

I would use my above-mentioned versions before reopening this issue.
